@backend_dotnet_HostAddress = http://localhost:5216

GET {{backend_dotnet_HostAddress}}/weatherforecast/
Accept: application/json

###

### Create Feedback
POST {{backend_dotnet_HostAddress}}/api/feedback
Content-Type: application/json

{
  "fullName": "Bushra Sayyed",
  "email": "bushra@example.com",
  "event": "React Workshop",
  "rating": 5,
  "comments": "Very useful workshop"
}

### Get Feedback
GET {{backend_dotnet_HostAddress}}/api/feedback
Accept: application/json

